### ISSUE TITLE
Frameless windows have wrong behavior on Windows

### ISSUE THREAD

**Issue by JohnLouderback** [trueinteractions/tint2#107]
``Window.WindowStyle = None`` is not the correct behavior for a frameless window on Windows. That will show a window with a thick border but no caption. I believe the expected behavior on Windows is a rectangular frame with no window chrome whatsoever. Typically this is done by applying ``WS_POPUP`` to the window styles, however, I think there's a better way, though I don't understand the solution 100%. If you check out the latest Spotify on Windows, you'll notice that their "frameless" window handles the elusive minimize and "unminimize" animations that windows with all the chrome typically enjoy whereas windows with ``WS_POPUP`` simply disappear when minimized - which is an ugly behavior. Supposedly this can be accomplished through the method described here: 
https://github.com/atom/atom-shell/issues/751 
I think the key there is much less the styles they're applying to the window, but that they're also rendering all the way from edge to edge of the window. Perhaps I'm wrong about that though.

**Comment by trevorlinton** [comment]
We've fixed this on the latest build of tint, it should be out later tonight if we can track down a misfiring event issue... I'll keep you updated.

**Comment by trevorlinton** [comment]
@JohnLouderback Your assessment is correct, the window (for WPF at least) needs AllowsTransparency = true and WindowStyle = None to work correctly.  Note that when you use transparency interop controls such as WPF's WebView are no longer allowed, fortunately we tested the chromium module and it has no troubles with transparent windows.

We've updated Tint to support the new transparent windows, set the background color to transparent and frame to none and the entire window will become transparent (minus whatever controls you place on it).

You can download the new version here:
https://github.com/trueinteractions/tint2/releases/tag/2.1.5

Here's an example we tested:
```javascript
require('Common');

var win = new Window();
var btn = new Button();
btn.title = "Foo";
win.appendChild(btn);
btn.left = btn.top = 0;
btn.width = 120;
btn.height = 20;
win.frame = false;
win.backgroundColor = 'transparent';
win.visible = true;
```

**Comment by JohnLouderback** [comment]
Using the code above, I get the same behavior as the previous version. I see an opaque white frame with just a re-sizable border. I downloaded the latest release and uninstalled the previous release to be sure.

**Comment by trevorlinton** [comment]
@JohnLouderback 

I checked my release version and it seems fine, I then realized we had to update the release on Github by editing it (I don't think github appreciates modifying a release afterwards), as I downloaded it from Github and it was still the original non-functional version.

Download the version here: http://www.trueinteractions.com/tint-2.1.6-x64-win.msi

I had to artificially bump the version number so the MSI installer will run properly, its still v2.1.5, note you'll need to do a full uninstall if you plan on installing 2.1.6, or wait for 2.1.7.  Either way. 

This should fix it.

**Comment by JohnLouderback** [comment]
Hmm. Transparency works perfectly now! Very exciting. The windows that are just frameless without transparency, however, still are working the way the previous version worked from what I'm seeing. I'm still seeing the window with resizable border.

**Comment by JohnLouderback** [comment]
Are you still seeing this behavior as well?

**Comment by trevorlinton** [comment]
Hi John,

I'm a bit confused as to what intended behavior you're trying to reach, did you want the content area to extend all the way to the top and sides of the window frame while keeping the window frame there?

Here's the various window frame options I can reproduce:

Normal frame:
![window_0](https://cloud.githubusercontent.com/assets/3111873/6976996/f95afde6-d970-11e4-873f-343ed9711ed7.png)

```backgroundColor='transparent', frame=false```
![window_1](https://cloud.githubusercontent.com/assets/3111873/6976998/f976799a-d970-11e4-91bf-29c918f7cffa.png)

```frame=false```
![window_2](https://cloud.githubusercontent.com/assets/3111873/6976999/f9793a54-d970-11e4-9b07-8d222f228829.png)

```frame=false, resizable=false```
![window_3](https://cloud.githubusercontent.com/assets/3111873/6977000/f979d568-d970-11e4-913c-ab2be7c0d4a2.png)


Was there another window type you're referring to?

**Comment by JohnLouderback** [comment]
Hi Trevor,

Doh! My mistake was not including ``resizable=false``! I apologize for telling you it didn't work. I guess separate from that, the answer to your first question is "yes". I was looking for a way to have a window with a normal frame where content covers the frame edge-to-edge like Atom and Spotify do. I just thought that the current frameless  implementation didn't work and it would be a good opportunity to implement something of that nature since it seems relatively easy and has the added benefits of things like minimize animations and such. Let me know your thoughts. Perhaps, if nothing else, I'll try my hand at playing with the bridge API and see if I'm able to tackle it myself. Translating between C++ and its JS equivalent is a little confusing to me still.

**Comment by trevorlinton** [comment]
No worries, if there are other features or needs feel free to reopen this issue.

**Comment by JohnLouderback** [comment]
For whatever it might be worth, I was able to accomplish what I wanted to do. I really have to say, this Bridge API is amazing stuff. I thought I'd post the code here for posterity. A quick note - this is supposed to have a drop shadow as well, but that doesn't appear to happen.
```javascript
require('Common');
var $ = process.bridge.dotnet;
var win = new Window();

var winChrome = new $.System.Windows.Shell.WindowChrome;

var winChromeGlassFrameThickness = new $.System.Windows.Thickness;
winChromeGlassFrameThickness.left = 0;
winChromeGlassFrameThickness.right = 0;
winChromeGlassFrameThickness.top = 0;
winChromeGlassFrameThickness.bottom = 1;

var winChromeCornerRad = new $.System.Windows.CornerRadius;
winChromeCornerRad.TopLeft = 2;
winChromeCornerRad.TopRight = 2;
winChromeCornerRad.BottomLeft = 2;
winChromeCornerRad.BottomRight = 2;

winChrome.CaptionHeight = 35;
winChrome.GlassFrameThickness = winChromeGlassFrameThickness;
winChrome.CornerRadius = winChromeCornerRad;

$.System.Windows.Shell.WindowChrome.SetWindowChrome(win.native, winChrome);

win.visible = true;
Chromium = require('chromium');
var webview = new Chromium();
win.appendChild(webview);
webview.left = webview.right = webview.top = webview.bottom = 0;
webview.location = "file://D://Projects//Tint Tests//Chromium//index.html";


```

**Comment by trevorlinton** [comment]
@JohnLouderback I'm glad its helpful! You can find more information on the .NET and OBJC bridge here (although its a bit out of date)

https://github.com/trueinteractions/tint2/wiki/Using-Objective-C-in-Tint
https://github.com/trueinteractions/tint2/wiki/Using-.NET-in-Tint
